# Shield Chart: 0.10.0
# OCI Registry: jfrog.idonthaveany.boats
cluster_config:
  # REQUIRED - The name of the cluster
  name: sysdig-eks-qa-9999-abcd
  # REQUIRED - Tags you want to apply to the metadata sent to the Sysdig Backend.
  tags:
    cluster: sysdig-eks-qa-9999-abcd
    vz-vsadid: abcd
    vz-vastid: "9999"
sysdig_endpoint:
  # REQUIRED IF NOT USING INSTALL.SH - The access key for the Sysdig Secure instance
  access_key:
host:
  resources:
    shield:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 750m
        memory: 750Mi
cluster:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1500m
      memory: 1536Mi
